"""
convert_to_tflite.py
====================
Convert the trained Sleep Apnea Fusion Model (.h5) to TensorFlow Lite
and generate a C header file for ESP32 deployment.

Pipeline:
  sleep_apnea_fusion_v3.h5
       |
       v
  sleep_apnea_fusion_v3.tflite   (quantized, optimized)
       |
       v
  sleep_apnea_model.h             (C byte array for ESP32 flash)

Usage:
  python convert_to_tflite.py
  python convert_to_tflite.py --quantize      # INT8 quantization for smaller model
  python convert_to_tflite.py --test           # Verify TFLite output matches .h5
"""

import os
import argparse
import numpy as np

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

import tensorflow as tf


# ===========================================================================
# CONFIGURATION
# ===========================================================================

BASE_DIR   = os.path.dirname(os.path.abspath(__file__))
MODEL_DIR  = os.path.join(BASE_DIR, "models")
ESP32_DIR  = os.path.join(BASE_DIR, "esp32_apnea_detector")

H5_PATH     = os.path.join(MODEL_DIR, "sleep_apnea_fusion_v3.h5")
TFLITE_PATH = os.path.join(MODEL_DIR, "sleep_apnea_fusion_v3.tflite")
C_HEADER    = os.path.join(ESP32_DIR, "sleep_apnea_model.h")


# ===========================================================================
# 1. CONVERT .h5 -> .tflite
# ===========================================================================

def convert_to_tflite(quantize=False):
    """
    Convert the Keras .h5 model to a TFLite flatbuffer.
    Optionally apply INT8 quantization for smaller ESP32 footprint.
    """
    print(f"\n[STEP 1] Loading model: {H5_PATH}")
    model = tf.keras.models.load_model(H5_PATH, compile=False)
    model.summary()

    print("\n[STEP 2] Converting to TensorFlow Lite...")
    converter = tf.lite.TFLiteConverter.from_keras_model(model)

    # Optimizations for microcontroller deployment
    converter.optimizations = [tf.lite.Optimize.DEFAULT]

    if quantize:
        print("   [INT8] Applying full integer quantization...")

        # Representative dataset for calibration
        def representative_dataset():
            for _ in range(100):
                audio   = np.random.randn(1, 32, 32, 1).astype(np.float32)
                vitals  = np.random.randn(1, 60, 2).astype(np.float32)
                # Make vitals realistic: SpO2 ~95-100, BPM ~50-100
                vitals[0, :, 0] = np.random.uniform(85, 100, 60)
                vitals[0, :, 1] = np.random.uniform(50, 110, 60)
                movement = np.random.uniform(0.8, 1.5, (1, 60, 1)).astype(np.float32)
                yield {
                    "audio_input": audio,
                    "max30102_input": vitals,
                    "mpu6050_input": movement
                }

        converter.representative_dataset = representative_dataset
        converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
        # By removing uint8 inference types, TFLite defaults to Float32 inputs/outputs,
        # but uses INT8 for all internal weights and operations.
    else:
        # Float16 quantization -- good balance of size vs accuracy
        converter.target_spec.supported_types = [tf.float16]

    tflite_model = converter.convert()

    os.makedirs(MODEL_DIR, exist_ok=True)
    with open(TFLITE_PATH, "wb") as f:
        f.write(tflite_model)

    size_kb = len(tflite_model) / 1024
    print(f"\n[SAVED] TFLite model: {TFLITE_PATH}")
    print(f"        Size: {size_kb:.1f} KB")

    return tflite_model


# ===========================================================================
# 2. CONVERT .tflite -> C HEADER FILE
# ===========================================================================

def generate_c_header(tflite_model):
    """
    Convert the TFLite flatbuffer into a C-style const unsigned char array
    that can be compiled directly into ESP32 firmware.
    """
    print(f"\n[STEP 3] Generating C header file: {C_HEADER}")

    os.makedirs(ESP32_DIR, exist_ok=True)

    hex_bytes = ", ".join(f"0x{b:02x}" for b in tflite_model)
    model_len = len(tflite_model)

    header_content = f"""/*
 * sleep_apnea_model.h
 * ====================
 * Auto-generated by convert_to_tflite.py
 * DO NOT EDIT MANUALLY.
 *
 * This file contains the TensorFlow Lite model as a C byte array
 * for deployment on ESP32 using TensorFlow Lite Micro.
 *
 * Model: Sleep Apnea Fusion v3 (3-sensor)
 * Inputs:
 *   1. Audio MFCC     : float32[1][32][32][1]
 *   2. MAX30102 SpO2/BPM: float32[1][60][2]
 *   3. MPU6050 Movement: float32[1][60][1]
 * Output:
 *   Apnea risk score  : float32[1][1]  (0.0 = healthy, 1.0 = severe)
 *
 * Size: {model_len} bytes ({model_len / 1024:.1f} KB)
 */

#ifndef SLEEP_APNEA_MODEL_H
#define SLEEP_APNEA_MODEL_H

const unsigned int sleep_apnea_model_len = {model_len};

alignas(8) const unsigned char sleep_apnea_model_data[] = {{
  {hex_bytes}
}};

#endif  // SLEEP_APNEA_MODEL_H
"""

    with open(C_HEADER, "w") as f:
        f.write(header_content)

    print(f"        Array name: sleep_apnea_model_data")
    print(f"        Array size: {model_len} bytes ({model_len / 1024:.1f} KB)")
    print(f"        [OK] Header saved!")

    return C_HEADER


# ===========================================================================
# 3. VERIFY TFLITE OUTPUT MATCHES ORIGINAL
# ===========================================================================

def verify_tflite():
    """
    Run inference with both the original .h5 model and the .tflite model
    on the same inputs and compare outputs.
    """
    print("\n[VERIFY] Comparing .h5 vs .tflite outputs...")

    # Load original model
    h5_model = tf.keras.models.load_model(H5_PATH, compile=False)

    # Load TFLite model
    interpreter = tf.lite.Interpreter(model_path=TFLITE_PATH)
    interpreter.allocate_tensors()

    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()

    # Map inputs by name (TFLite may reorder them)
    input_map = {}
    for inp in input_details:
        name = inp['name'].lower()
        if "audio" in name:
            input_map["audio"] = inp
        elif "max30102" in name:
            input_map["max30102"] = inp
        elif "mpu6050" in name:
            input_map["mpu6050"] = inp

    print(f"\n   TFLite Inputs (mapped by name):")
    for key, inp in input_map.items():
        print(f"     {key:10s} -> idx={inp['index']} shape={inp['shape']} dtype={inp['dtype']}")
    print(f"   TFLite Outputs:")
    for out in output_details:
        print(f"     [{out['index']}] {out['name']:30s} shape={out['shape']} dtype={out['dtype']}")

    # Generate test samples
    test_cases = [
        ("Healthy", 0.0, 98.0, 65.0, 1.0),
        ("Moderate", 0.5, 90.0, 85.0, 1.8),
        ("Severe",  1.0, 82.0, 110.0, 3.5),
    ]

    print(f"\n   {'Profile':<12} {'H5 Score':>10} {'TFLite Score':>14} {'Diff':>8}")
    print("   " + "-" * 48)

    for name, audio_shift, spo2_val, bpm_val, move_val in test_cases:
        audio = (np.random.randn(1, 32, 32, 1).astype(np.float32) * 0.3) + audio_shift
        vitals = np.zeros((1, 60, 2), dtype=np.float32)
        vitals[0, :, 0] = spo2_val
        vitals[0, :, 1] = bpm_val
        movement = np.full((1, 60, 1), move_val, dtype=np.float32)

        # H5 prediction
        h5_pred = h5_model.predict([audio, vitals, movement], verbose=0)[0][0]

        # TFLite prediction (use name-mapped indices)
        interpreter.set_tensor(input_map["audio"]['index'], audio)
        interpreter.set_tensor(input_map["max30102"]['index'], vitals)
        interpreter.set_tensor(input_map["mpu6050"]['index'], movement)
        interpreter.invoke()
        tflite_pred = interpreter.get_tensor(output_details[0]['index'])[0][0]

        diff = abs(h5_pred - tflite_pred)
        print(f"   {name:<12} {h5_pred:>10.4f} {tflite_pred:>14.4f} {diff:>8.4f}")

    print("\n   [OK] Verification complete!")
    print("   Small differences are normal (float16 quantization rounding).\n")


# ===========================================================================
# MAIN
# ===========================================================================

def main():
    parser = argparse.ArgumentParser(description="Convert Sleep Apnea model for ESP32")
    parser.add_argument("--quantize", action="store_true",
                        help="Apply INT8 quantization (smaller but less precise)")
    parser.add_argument("--test", action="store_true",
                        help="Verify TFLite output matches original model")
    args = parser.parse_args()

    print("=" * 60)
    print("  Sleep Apnea Model -> ESP32 Conversion Pipeline")
    print("=" * 60)

    if not os.path.isfile(H5_PATH):
        print(f"\n[ERROR] Model not found: {H5_PATH}")
        print("        Run fusion_model.py --demo or prepare_ucd_data.py --train first.")
        return

    # Step 1+2: Convert to TFLite
    tflite_model = convert_to_tflite(quantize=args.quantize)

    # Step 3: Generate C header
    generate_c_header(tflite_model)

    # Step 4: Verify (optional)
    if args.test:
        verify_tflite()

    print("\n" + "=" * 60)
    print("  CONVERSION COMPLETE!")
    print("=" * 60)
    print(f"\n  Files created (no existing files modified):")
    print(f"    1. {TFLITE_PATH}")
    print(f"    2. {C_HEADER}")
    print(f"\n  Next: Flash esp32_apnea_detector/ to your ESP32!")
    print()


if __name__ == "__main__":
    main()
